/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-06 16:01:23
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.biz.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.scf.loan.common.base.dto.PageResult;
import com.scf.loan.dal.entity.BillEntity;
import com.scf.loan.dal.mapper.BillMapper;
import com.scf.loan.common.dto.BillPageDTO;
import com.scf.loan.common.dto.BillDTO;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.mockito.Spy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * BillService单元测试
 */
public class BillServiceTest {

    private static final Logger logger = LoggerFactory.getLogger(BillServiceTest.class);

    @InjectMocks
    @Spy
    private BillServiceImpl billService;

    @Mock
    private BillMapper billMapper;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    /**
     * 测试批量创建Bill
     */
    @Test
    public void testBatchCreateBill() {
        logger.info("开始执行测试批量创建Bill");
        
        List<BillEntity> entities = new ArrayList<>();
        BillEntity entity = new BillEntity();
        entity.setId(1L);
        entities.add(entity);

        // 模拟 saveBatch 返回 true
        doReturn(true).when(billService).saveBatch(entities);

        boolean result = billService.batchCreateBill(entities);
        assertTrue(result);
        
        verify(billService, times(1)).saveBatch(entities);
        
        logger.info("测试批量创建Bill执行完成");
    }

    /**
     * 测试批量更新Bill
     */
    @Test
    public void testBatchUpdateBill() {
        logger.info("开始执行测试批量更新Bill");
        
        List<BillEntity> entities = new ArrayList<>();
        BillEntity entity = new BillEntity();
        entity.setId(1L);
        entities.add(entity);

        // 模拟 updateBatchById 返回 true
        doReturn(true).when(billService).updateBatchById(entities);

        boolean result = billService.batchUpdateBill(entities);
        assertTrue(result);
        
        verify(billService, times(1)).updateBatchById(entities);
        
        logger.info("测试批量更新Bill执行完成");
    }

    /**
     * 测试分页查询Bill
     */
    @Test
    @SuppressWarnings("unchecked")
    public void testPageBill() {
        logger.info("开始执行测试分页查询Bill");

        BillPageDTO pageDTO = new BillPageDTO();
        pageDTO.setPage(1);
        pageDTO.setSize(10);
        pageDTO.setId(1L);
        pageDTO.setStartTime(LocalDateTime.now().minusDays(1));
        pageDTO.setEndTime(LocalDateTime.now());

        BillEntity entity = new BillEntity();
        entity.setId(1L);
        entity.setCreatedAt(LocalDateTime.now());
        
        Page<BillEntity> page = new Page<>();
        page.setRecords(Collections.singletonList(entity));
        page.setTotal(1);

        // 模拟 page 方法
        doReturn(page).when(billService).page(any(Page.class), any(QueryWrapper.class));

        PageResult<BillDTO> result = billService.pageBill(pageDTO);
        
        assertNotNull(result);
        assertEquals(1, result.getTotal());
        assertEquals(1, result.getRecords().size());
        assertEquals(1L, result.getRecords().get(0).getId());

        verify(billService, times(1)).page(any(Page.class), any(QueryWrapper.class));

        logger.info("测试分页查询Bill执行完成");
    }

    /**
     * 测试分页查询Bill - 空条件
     */
    @Test
    @SuppressWarnings("unchecked")
    public void testPageBillWithEmptyConditions() {
        logger.info("开始执行测试分页查询Bill - 空条件");

        BillPageDTO pageDTO = new BillPageDTO();
        pageDTO.setPage(1);
        pageDTO.setSize(10);
        // 不设置任何查询条件

        BillEntity entity = new BillEntity();
        entity.setId(1L);
        entity.setCreatedAt(LocalDateTime.now());
        
        Page<BillEntity> page = new Page<>();
        page.setRecords(Collections.singletonList(entity));
        page.setTotal(1);

        // 模拟 page 方法
        doReturn(page).when(billService).page(any(Page.class), any(QueryWrapper.class));

        PageResult<BillDTO> result = billService.pageBill(pageDTO);
        
        assertNotNull(result);
        assertEquals(1, result.getTotal());
        assertEquals(1, result.getRecords().size());

        verify(billService, times(1)).page(any(Page.class), any(QueryWrapper.class));

        logger.info("测试分页查询Bill - 空条件 执行完成");
    }
}