/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-06 14:54:16
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.biz.service.impl;

import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.scf.loan.common.dto.PageResult;
import com.scf.loan.dal.entity.FinancingOrderEntity;
import com.scf.loan.dal.mapper.FinancingOrderMapper;
import com.scf.loan.common.dto.FinancingOrderPageDTO;
import com.scf.loan.common.dto.FinancingOrderDTO;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.mockito.Spy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * FinancingOrderService单元测试
 */
public class FinancingOrderServiceTest {

    private static final Logger logger = LoggerFactory.getLogger(FinancingOrderServiceTest.class);

    @InjectMocks
    @Spy
    private FinancingOrderServiceImpl financingorderService;

    @Mock
    private FinancingOrderMapper financingorderMapper;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    /**
     * 测试批量创建FinancingOrder
     */
    @Test
    public void testBatchCreateFinancingOrder() {
        logger.info("开始执行测试批量创建FinancingOrder");
        
        List<FinancingOrderEntity> entities = new ArrayList<>();
        FinancingOrderEntity entity = new FinancingOrderEntity();
        entity.setId(1L);
        entities.add(entity);

        // 模拟 saveBatch 返回 true
        doReturn(true).when(financingorderService).saveBatch(entities);

        boolean result = financingorderService.batchCreateFinancingOrder(entities);
        assertTrue(result);
        
        verify(financingorderService, times(1)).saveBatch(entities);
        
        logger.info("测试批量创建FinancingOrder执行完成");
    }

    /**
     * 测试批量更新FinancingOrder
     */
    @Test
    public void testBatchUpdateFinancingOrder() {
        logger.info("开始执行测试批量更新FinancingOrder");
        
        List<FinancingOrderEntity> entities = new ArrayList<>();
        FinancingOrderEntity entity = new FinancingOrderEntity();
        entity.setId(1L);
        entities.add(entity);

        // 模拟 updateBatchById 返回 true
        doReturn(true).when(financingorderService).updateBatchById(entities);

        boolean result = financingorderService.batchUpdateFinancingOrder(entities);
        assertTrue(result);
        
        verify(financingorderService, times(1)).updateBatchById(entities);
        
        logger.info("测试批量更新FinancingOrder执行完成");
    }

    /**
     * 测试分页查询FinancingOrder
     */
    @Test
    @SuppressWarnings("unchecked")
    public void testPageFinancingOrder() {
        logger.info("开始执行测试分页查询FinancingOrder");

        FinancingOrderPageDTO pageDTO = new FinancingOrderPageDTO();
        pageDTO.setPage(1);
        pageDTO.setSize(10);
        pageDTO.setId(1L);
        pageDTO.setStartTime(LocalDateTime.now().minusDays(1));
        pageDTO.setEndTime(LocalDateTime.now());

        FinancingOrderEntity entity = new FinancingOrderEntity();
        entity.setId(1L);
        entity.setCreatedAt(LocalDateTime.now());
        
        Page<FinancingOrderEntity> page = new Page<>();
        page.setRecords(Collections.singletonList(entity));
        page.setTotal(1);

        // 模拟 page 方法
        doReturn(page).when(financingorderService).page(any(Page.class), any(QueryWrapper.class));

        PageResult<FinancingOrderDTO> result = financingorderService.pageFinancingOrder(pageDTO);
        
        assertNotNull(result);
        assertEquals(1, result.getTotal());
        assertEquals(1, result.getRecords().size());
        assertEquals(1L, result.getRecords().get(0).getId());

        verify(financingorderService, times(1)).page(any(Page.class), any(QueryWrapper.class));

        logger.info("测试分页查询FinancingOrder执行完成");
    }

    /**
     * 测试分页查询FinancingOrder - 空条件
     */
    @Test
    @SuppressWarnings("unchecked")
    public void testPageFinancingOrderWithEmptyConditions() {
        logger.info("开始执行测试分页查询FinancingOrder - 空条件");

        FinancingOrderPageDTO pageDTO = new FinancingOrderPageDTO();
        pageDTO.setPage(1);
        pageDTO.setSize(10);
        // 不设置任何查询条件

        FinancingOrderEntity entity = new FinancingOrderEntity();
        entity.setId(1L);
        entity.setCreatedAt(LocalDateTime.now());
        
        Page<FinancingOrderEntity> page = new Page<>();
        page.setRecords(Collections.singletonList(entity));
        page.setTotal(1);

        // 模拟 page 方法
        doReturn(page).when(financingorderService).page(any(Page.class), any(QueryWrapper.class));

        PageResult<FinancingOrderDTO> result = financingorderService.pageFinancingOrder(pageDTO);
        
        assertNotNull(result);
        assertEquals(1, result.getTotal());
        assertEquals(1, result.getRecords().size());

        verify(financingorderService, times(1)).page(any(Page.class), any(QueryWrapper.class));

        logger.info("测试分页查询FinancingOrder - 空条件 执行完成");
    }
}