/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-06 09:04:21
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.biz.service.impl;

import com.scf.loan.biz.service.FinancingOrderService;
import com.scf.loan.dal.entity.FinancingOrderEntity;
import com.scf.loan.common.dto.PageResult;
import com.scf.loan.common.dto.FinancingOrderPageDTO;
import com.scf.loan.common.dto.FinancingOrderDTO;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

/**
 * FinancingOrderService单元测试
 */
public class FinancingOrderServiceTest {

    private static final Logger logger = LoggerFactory.getLogger(FinancingOrderServiceTest.class);

    @Mock
    private FinancingOrderService financingorderService;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    /**
     * 测试批量创建FinancingOrder
     */
    @Test
    public void testBatchCreateFinancingOrder() {
        logger.info("开始执行测试批量创建FinancingOrder");
        
        List<FinancingOrderEntity> entities = new ArrayList<>();
        
        // 创建测试数据
        FinancingOrderEntity entity1 = new FinancingOrderEntity();
        // 设置测试数据
        // entity1.setXXX(XXX);
        entities.add(entity1);
        
        FinancingOrderEntity entity2 = new FinancingOrderEntity();
        // 设置测试数据
        // entity2.setXXX(XXX);
        entities.add(entity2);
        
        // 模拟返回值
        when(financingorderService.batchCreateFinancingOrder(entities)).thenReturn(true);
        
        boolean result = financingorderService.batchCreateFinancingOrder(entities);
        assertTrue(result);
        
        // 验证方法调用
        verify(financingorderService, times(1)).batchCreateFinancingOrder(entities);
        
        logger.info("测试批量创建FinancingOrder执行完成");
    }

    /**
     * 测试批量更新FinancingOrder
     */
    @Test
    public void testBatchUpdateFinancingOrder() {
        logger.info("开始执行测试批量更新FinancingOrder");
        
        // 创建测试数据
        List<FinancingOrderEntity> entities = new ArrayList<>();
        
        FinancingOrderEntity entity1 = new FinancingOrderEntity();
        // 设置测试数据
        // entity1.setXXX(XXX);
        entities.add(entity1);
        
        // 模拟返回值
        when(financingorderService.batchUpdateFinancingOrder(entities)).thenReturn(true);
        
        boolean result = financingorderService.batchUpdateFinancingOrder(entities);
        assertTrue(result);
        
        // 验证方法调用
        verify(financingorderService, times(1)).batchUpdateFinancingOrder(entities);
        
        logger.info("测试批量更新FinancingOrder执行完成");
    }

    /**
     * 测试分页查询FinancingOrder
     */
    @Test
    public void testPageFinancingOrder() {
        logger.info("开始执行测试分页查询FinancingOrder");
        
        FinancingOrderPageDTO dto = new FinancingOrderPageDTO();
        dto.setPage(1);
        dto.setSize(10);
        PageResult<FinancingOrderDTO> mockResult = new PageResult<>();
        mockResult.setRecords(new ArrayList<FinancingOrderDTO>());
        mockResult.setPage(1);
        mockResult.setSize(10);
        when(financingorderService.pageFinancingOrder(dto)).thenReturn(mockResult);
        
        PageResult<FinancingOrderDTO> pageResult = financingorderService.pageFinancingOrder(dto);
        
        assertNotNull(pageResult);
        verify(financingorderService, times(1)).pageFinancingOrder(dto);
        logger.info("测试分页查询FinancingOrder执行完成");
    }
}