/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-06 16:01:23
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.biz.convert;

import com.scf.loan.dal.entity.BillEntity;
import com.scf.loan.common.dto.BillDTO;

/**
 * Bill对象转换工具
 */
public final class BillConverter {

    private BillConverter() {}

    public static BillDTO toDTO(BillEntity e) {
        if (e == null) return null;
        BillDTO d = new BillDTO();
        d.setId(e.getId());
        d.setFinancingOrderId(e.getFinancingOrderId());
        d.setBillId(e.getBillId());
        d.setBillPeriod(e.getBillPeriod());
        d.setBillStatus(e.getBillStatus());
        d.setStartDate(e.getStartDate());
        d.setDueDate(e.getDueDate());
        d.setTotalAmount(e.getTotalAmount());
        d.setPrincipalAmount(e.getPrincipalAmount());
        d.setInterestAmount(e.getInterestAmount());
        d.setOtherAmount(e.getOtherAmount());
        d.setPaidAmount(e.getPaidAmount());
        d.setRemainingAmount(e.getRemainingAmount());
        d.setOverdueDays(e.getOverdueDays());
        d.setStateChangeTime(e.getStateChangeTime());
        d.setExtInfo(e.getExtInfo());
        d.setCreatedAt(e.getCreatedAt());
        d.setUpdatedAt(e.getUpdatedAt());
        d.setCreatedBy(e.getCreatedBy());
        d.setUpdatedBy(e.getUpdatedBy());
        d.setDelFlag(e.getDelFlag());
        d.setRevision(e.getRevision());
        return d;
    }

    public static BillEntity toEntity(BillDTO d) {
        if (d == null) return null;
        BillEntity e = new BillEntity();
        e.setId(d.getId());
        e.setFinancingOrderId(d.getFinancingOrderId());
        e.setBillId(d.getBillId());
        e.setBillPeriod(d.getBillPeriod());
        e.setBillStatus(d.getBillStatus());
        e.setStartDate(d.getStartDate());
        e.setDueDate(d.getDueDate());
        e.setTotalAmount(d.getTotalAmount());
        e.setPrincipalAmount(d.getPrincipalAmount());
        e.setInterestAmount(d.getInterestAmount());
        e.setOtherAmount(d.getOtherAmount());
        e.setPaidAmount(d.getPaidAmount());
        e.setRemainingAmount(d.getRemainingAmount());
        e.setOverdueDays(d.getOverdueDays());
        e.setStateChangeTime(d.getStateChangeTime());
        e.setExtInfo(d.getExtInfo());
        e.setCreatedAt(d.getCreatedAt());
        e.setUpdatedAt(d.getUpdatedAt());
        e.setCreatedBy(d.getCreatedBy());
        e.setUpdatedBy(d.getUpdatedBy());
        e.setDelFlag(d.getDelFlag());
        e.setRevision(d.getRevision());
        return e;
    }
}