/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-06 09:04:21
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.biz.convert;

import com.scf.loan.dal.entity.FinancingOrderEntity;
import com.scf.loan.common.dto.FinancingOrderDTO;

/**
 * FinancingOrder对象转换工具
 */
public final class FinancingOrderConverter {

    private FinancingOrderConverter() {}

    public static FinancingOrderDTO toDTO(FinancingOrderEntity e) {
        if (e == null) return null;
        FinancingOrderDTO d = new FinancingOrderDTO();
        d.setId(e.getId());
        d.setUid(e.getUid());
        d.setEnv(e.getEnv());
        d.setFinancingOrderId(e.getFinancingOrderId());
        d.setCreditContractType(e.getCreditContractType());
        d.setCreditContractId(e.getCreditContractId());
        d.setMerTransNo(e.getMerTransNo());
        d.setContractNo(e.getContractNo());
        d.setApplyStatus(e.getApplyStatus());
        d.setLoanConfirmStatus(e.getLoanConfirmStatus());
        d.setRepayStatus(e.getRepayStatus());
        d.setLoanTime(e.getLoanTime());
        d.setClearUpTime(e.getClearUpTime());
        d.setLoanAmount(e.getLoanAmount());
        d.setStateChangeTime(e.getStateChangeTime());
        d.setExtInfo(e.getExtInfo());
        d.setCreatedAt(e.getCreatedAt());
        d.setUpdatedAt(e.getUpdatedAt());
        d.setCreatedBy(e.getCreatedBy());
        d.setUpdatedBy(e.getUpdatedBy());
        d.setDelFlag(e.getDelFlag());
        d.setRevision(e.getRevision());
        d.setStartDate(e.getStartDate());
        d.setDueDate(e.getDueDate());
        return d;
    }

    public static FinancingOrderEntity toEntity(FinancingOrderDTO d) {
        if (d == null) return null;
        FinancingOrderEntity e = new FinancingOrderEntity();
        e.setId(d.getId());
        e.setUid(d.getUid());
        e.setEnv(d.getEnv());
        e.setFinancingOrderId(d.getFinancingOrderId());
        e.setCreditContractType(d.getCreditContractType());
        e.setCreditContractId(d.getCreditContractId());
        e.setMerTransNo(d.getMerTransNo());
        e.setContractNo(d.getContractNo());
        e.setApplyStatus(d.getApplyStatus());
        e.setLoanConfirmStatus(d.getLoanConfirmStatus());
        e.setRepayStatus(d.getRepayStatus());
        e.setLoanTime(d.getLoanTime());
        e.setClearUpTime(d.getClearUpTime());
        e.setLoanAmount(d.getLoanAmount());
        e.setStateChangeTime(d.getStateChangeTime());
        e.setExtInfo(d.getExtInfo());
        e.setCreatedAt(d.getCreatedAt());
        e.setUpdatedAt(d.getUpdatedAt());
        e.setCreatedBy(d.getCreatedBy());
        e.setUpdatedBy(d.getUpdatedBy());
        e.setDelFlag(d.getDelFlag());
        e.setRevision(d.getRevision());
        e.setStartDate(d.getStartDate());
        e.setDueDate(d.getDueDate());
        return e;
    }
}