/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-06 16:01:23
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.biz.service;

import com.baomidou.mybatisplus.extension.service.IService;
 import com.scf.loan.dal.entity.BillEntity;
 import com.scf.loan.common.base.dto.PageResult;
 import com.scf.loan.common.dto.BillPageDTO;
 import com.scf.loan.common.dto.BillDTO;

import java.util.List;

/**
 * BillEntity 服务接口
 */
public interface BillService extends IService<BillEntity> {

    /**
     * 批量创建Bill
     * @param entities BillEntity实体列表
     * @return 是否创建成功
     */
    boolean batchCreateBill(List<BillEntity> entities);

    /**
     * 批量更新Bill
     * @param entities BillEntity实体列表
     * @return 是否更新成功
     */
    boolean batchUpdateBill(List<BillEntity> entities);

    /**
     * 分页查询Bill
     * @param dto 分页查询请求
     * @return 分页结果
     */
    PageResult<BillDTO> pageBill(BillPageDTO dto);
}