/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-05 15:05:23
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.biz.service;

import com.baomidou.mybatisplus.extension.service.IService;
 import com.scf.loan.dal.entity.FinancingOrderEntity;
 import com.scf.loan.common.dto.PageResult;
 import com.scf.loan.common.dto.FinancingOrderPageDTO;
 import com.scf.loan.common.dto.FinancingOrderDTO;

import java.util.List;

/**
 * FinancingOrderEntity 服务接口
 */
public interface FinancingOrderService extends IService<FinancingOrderEntity> {

    /**
     * 批量创建FinancingOrder
     * @param entities FinancingOrderEntity实体列表
     * @return 是否创建成功
     */
    boolean batchCreateFinancingOrder(List<FinancingOrderEntity> entities);

    /**
     * 批量更新FinancingOrder
     * @param entities FinancingOrderEntity实体列表
     * @return 是否更新成功
     */
    boolean batchUpdateFinancingOrder(List<FinancingOrderEntity> entities);

    /**
     * 分页查询FinancingOrder
     * @param dto 分页查询请求
     * @return 分页结果
     */
    PageResult<FinancingOrderDTO> pageFinancingOrder(FinancingOrderPageDTO dto);
}