/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-06 16:01:23
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.dal.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.scf.loan.dal.entity.BillEntity;

/**
 * BillEntity Mapper接口
 */
public interface BillMapper extends BaseMapper<BillEntity> {
}