/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-06 16:01:23
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.common.dto;

import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * Bill分页查询请求
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class BillPageDTO extends BasePageRequestDTO {
    private static final long serialVersionUID = 1L;
}