/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-05 15:21:21
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.common.dto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import com.scf.loan.common.dto.BasePageRequestDTO;
import java.io.Serializable;

/**
 * FinancingOrder分页查询请求
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class FinancingOrderPageDTO extends BasePageRequestDTO implements Serializable {
    private static final long serialVersionUID = 1L;
}