/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-06 15:29:21
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.common.dto;

import com.scf.loan.common.base.dto.BasePageRequestDTO;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * FinancingOrder分页查询请求
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class FinancingOrderPageDTO extends BasePageRequestDTO {
    private static final long serialVersionUID = 1L;
}