/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-06 16:01:23
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.dal.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * 账单表
 */
@Data
@TableName("t_scf_bill")
public class BillEntity {

    /**
     * 主键ID
     */
    @TableId(type = IdType.AUTO)
    private Long id;

    /**
     * 融资订单号
     */
    private String financingOrderId;

    /**
     * 账单ID
     */
    private String billId;

    /**
     * 期次
     */
    private Integer billPeriod;

    /**
     * 账单状态: 待还款(waitRepay), 部分还款(partRepaid), 已还款(repaid), 已逾期(overdue), 已结清(cleared)
     */
    private String billStatus;

    /**
     * 账单开始日期 yyyy-MM-dd
     */
    private String startDate;

    /**
     * 账单到期日期 yyyy-MM-dd
     */
    private String dueDate;

    /**
     * 账单总金额(分)
     */
    private Long totalAmount;

    /**
     * 本金金额(分)
     */
    private Long principalAmount;

    /**
     * 利息金额(分)
     */
    private Long interestAmount;

    /**
     * 其他费用金额(分)
     */
    private Long otherAmount;

    /**
     * 已还金额(分)
     */
    private Long paidAmount;

    /**
     * 剩余金额(分)
     */
    private Long remainingAmount;

    /**
     * 逾期天数
     */
    private Integer overdueDays;

    /**
     * 状态最近一次变更时间
     */
    private LocalDateTime stateChangeTime;

    /**
     * 扩展信息
     */
    private String extInfo;

    /**
     * 创建时间
     */
    private LocalDateTime createdAt;

    /**
     * 更新时间
     */
    private LocalDateTime updatedAt;

    /**
     * 创建人
     */
    private String createdBy;

    /**
     * 更新人
     */
    private String updatedBy;

    /**
     * 删除标志 0:有效 1:无效
     */
    private Integer delFlag;

    /**
     * 乐观锁版本号
     */
    private Integer revision;

}