/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-06 16:01:23
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.biz.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.scf.loan.biz.service.BillService;
import com.scf.loan.dal.entity.BillEntity;
import com.scf.loan.dal.mapper.BillMapper;
import com.scf.loan.common.dto.PageResult;
import com.scf.loan.common.dto.BillPageDTO;
import com.scf.loan.common.dto.BillDTO;
import com.scf.loan.biz.convert.BillConverter;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * BillEntity 服务实现类
 */
@Service
public class BillServiceImpl extends ServiceImpl<BillMapper, BillEntity> implements BillService {

    @Override
    public boolean batchCreateBill(List<BillEntity> entities) {
        return saveBatch(entities);
    }

    @Override
    public boolean batchUpdateBill(List<BillEntity> entities) {
        return updateBatchById(entities);
    }

    @Override
    public PageResult<BillDTO> pageBill(BillPageDTO dto) {
        QueryWrapper<BillEntity> qw = new QueryWrapper<>();
        if (dto.getId() != null) {
            qw.eq("id", dto.getId());
        }
        if (dto.getStartTime() != null) {
            qw.ge("created_at", dto.getStartTime());
        }
        if (dto.getEndTime() != null) {
            qw.le("created_at", dto.getEndTime());
        }
        Page<BillEntity> p = page(new Page<>(dto.getPage(), dto.getSize()), qw);
        java.util.List<BillDTO> dtos = new java.util.ArrayList<>();
        for (BillEntity e : p.getRecords()) {
            dtos.add(BillConverter.toDTO(e));
        }
        return PageResult.of(dtos, p.getTotal(), dto.getPage(), dto.getSize());
    }
}