/**
 * Generated by skill: db-generate v1.0.0
 * Since: 2026-02-06 09:33:49
 * Do not modify directly; regenerate via skills if changes are needed.
 * If manual changes are necessary, document @version, @since and change reasons in skill docs.
 */
package com.scf.loan.biz.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.scf.loan.biz.service.FinancingOrderService;
import com.scf.loan.dal.entity.FinancingOrderEntity;
import com.scf.loan.dal.mapper.FinancingOrderMapper;
import com.scf.loan.common.dto.PageResult;
import com.scf.loan.common.dto.FinancingOrderPageDTO;
import com.scf.loan.common.dto.FinancingOrderDTO;
import com.scf.loan.biz.convert.FinancingOrderConverter;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * FinancingOrderEntity 服务实现类
 */
@Service
public class FinancingOrderServiceImpl extends ServiceImpl<FinancingOrderMapper, FinancingOrderEntity> implements FinancingOrderService {

    @Override
    public boolean batchCreateFinancingOrder(List<FinancingOrderEntity> entities) {
        return saveBatch(entities);
    }

    @Override
    public boolean batchUpdateFinancingOrder(List<FinancingOrderEntity> entities) {
        return updateBatchById(entities);
    }

    @Override
    public PageResult<FinancingOrderDTO> pageFinancingOrder(FinancingOrderPageDTO dto) {
        QueryWrapper<FinancingOrderEntity> qw = new QueryWrapper<>();
        if (dto.getId() != null) {
            qw.eq("id", dto.getId());
        }
        if (dto.getStartTime() != null) {
            qw.ge("created_at", dto.getStartTime());
        }
        if (dto.getEndTime() != null) {
            qw.le("created_at", dto.getEndTime());
        }
        Page<FinancingOrderEntity> p = page(new Page<>(dto.getPage(), dto.getSize()), qw);
        java.util.List<FinancingOrderDTO> dtos = new java.util.ArrayList<>();
        for (FinancingOrderEntity e : p.getRecords()) {
            dtos.add(FinancingOrderConverter.toDTO(e));
        }
        return PageResult.of(dtos, p.getTotal(), dto.getPage(), dto.getSize());
    }
}