package com.scf.loan.common.enums;

import com.baomidou.mybatisplus.annotation.EnumValue;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 审批状态
 *
 * Generated by skill: enum-gen
 */
@Getter
@AllArgsConstructor
public enum ApplyEnum {

    /**
     * 审批中
     */
    APPLYING("applying", "审批中"),
    /**
     * 审批失败
     */
    REFUSED("refused", "审批失败"),
    /**
     * 审批成功
     */
    ACCEPT("accept", "审批成功");

    @EnumValue
    private final String code;

    @JsonValue
    private final String desc;
    
    public static ApplyEnum of(String value) {
        for (ApplyEnum item : values()) {
            if (item.code.equals(value)) {
                return item;
            }
        }
        return null;
    }
}