package com.scf.loan.common.enums;

import com.baomidou.mybatisplus.annotation.EnumValue;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 账单状态:
 *
 * Generated by skill: enum-gen
 */
@Getter
@AllArgsConstructor
public enum BillEnum {

    /**
     * 待还款
     */
    WAIT_REPAY("waitRepay", "待还款"),
    /**
     * 部分还款
     */
    PART_REPAID("partRepaid", "部分还款"),
    /**
     * 已还款
     */
    REPAID("repaid", "已还款"),
    /**
     * 已逾期
     */
    OVERDUE("overdue", "已逾期"),
    /**
     * 已结清
     */
    CLEARED("cleared", "已结清");

    @EnumValue
    private final String code;

    @JsonValue
    private final String desc;
    
    public static BillEnum of(String value) {
        for (BillEnum item : values()) {
            if (item.code.equals(value)) {
                return item;
            }
        }
        return null;
    }
}