package com.scf.loan.common.enums;

import com.baomidou.mybatisplus.annotation.EnumValue;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 删除标志
 *
 * Generated by skill: enum-gen
 */
@Getter
@AllArgsConstructor
public enum DelFlagEnum {

    /**
     * 有效
     */
    STATUS_0(0, "有效"),
    /**
     * 无效
     */
    STATUS_1(1, "无效");

    @EnumValue
    private final Integer code;

    @JsonValue
    private final String desc;
    
    public static DelFlagEnum of(Integer value) {
        for (DelFlagEnum item : values()) {
            if (item.code.equals(value)) {
                return item;
            }
        }
        return null;
    }
}