package com.scf.loan.common.enums;

import com.baomidou.mybatisplus.annotation.EnumValue;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 放款申请中(loaning)，放款申请失败(loanFailed)，放款申请成功(loanSuccess)
 *
 * Generated by skill: enum-gen
 */
@Getter
@AllArgsConstructor
public enum LoanConfirmEnum {

    /**
     * 放款申请中
     */
    LOANING("loaning", "放款申请中"),
    /**
     * 放款申请失败
     */
    LOAN_FAILED("loanFailed", "放款申请失败"),
    /**
     * 放款申请成功
     */
    LOAN_SUCCESS("loanSuccess", "放款申请成功");

    @EnumValue
    private final String code;

    @JsonValue
    private final String desc;
    
    public static LoanConfirmEnum of(String value) {
        for (LoanConfirmEnum item : values()) {
            if (item.code.equals(value)) {
                return item;
            }
        }
        return null;
    }
}