package com.scf.loan.common.enums;

import com.baomidou.mybatisplus.annotation.EnumValue;
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 还款状态:
 *
 * Generated by skill: enum-gen
 */
@Getter
@AllArgsConstructor
public enum RepayEnum {

    /**
     * 还款中
     */
    REPAYING("repaying", "还款中"),
    /**
     * 逾期中
     */
    OVER_DUE("overDue", "逾期中"),
    /**
     * 已结清
     */
    CLEAR_UP("clearUp", "已结清");

    @EnumValue
    private final String code;

    @JsonValue
    private final String desc;
    
    public static RepayEnum of(String value) {
        for (RepayEnum item : values()) {
            if (item.code.equals(value)) {
                return item;
            }
        }
        return null;
    }
}